version: "3.8"

networks:
  raspi_network:
    driver: bridge

services:
  pibot:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    restart: always
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    volumes:
      - .:/app
    networks:
      - raspi_network
    ports:
      - "5000:5000"
    command: python3 app.py

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - raspi_network

volumes:
  portainer_data:
