FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3-pip python3-rpi.gpio && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /app

RUN pip install --no-cache-dir flask pytest python-dotenv

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

CMD ["python3", "pibot.py"]