# Use the official Python image
FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3-pip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /app

RUN pip install --no-cache-dir flask python-dotenv

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

CMD ["flask", "run", "--host=0.0.0.0"]