networks:
  raspi_network:
    driver: bridge

services:
  pibot:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    restart: always
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - BUTTON_DELAY=${BUTTON_DELAY}
      - FLASK_PORT=${FLASK_PORT}
    volumes:
      - .:/app
    networks:
      - raspi_network
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    command: python3 app.py

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - raspi_network

volumes:
  portainer_data:
